apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hieuboyfc@gmail.com # Thay đổi email để nhận thông báo từ Let's Encrypt
    privateKeySecretRef:
      name: letsencrypt-prod # Tên secret chứa khóa riêng của ACME
    solvers:
      - http01:
          ingress:
            class: nginx # Tên lớp ingress mà cert-manager sẽ sử dụng

# kubectl get clusterissuer letsencrypt-prod
# kubectl describe clusterissuer letsencrypt-prod