apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.zimji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443

# kubectl get ingress -A
# kubectl get ingress argocd-ingress -n argocd
# kubectl describe ingress argocd-ingress -n argocd
# kubectl delete ingress argocd-ingress -n argocd