apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.zimji.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 8881
  tls:
    - hosts:
        - argocd.zimji.com
      secretName: argocd-secret

# kubectl get ingress -A
# kubectl get ingress argocd-ingress -n argocd
# kubectl describe ingress argocd-ingress -n argocd
# kubectl delete ingress argocd-ingress -n argocd

# kubectl get secret -A
# kubectl get secret argocd-secret -n argocd
# kubectl describe secret argocd-secret -n argocd
# kubectl delete secret argocd-secret -n argocd