server:
  port: 1997
  # address: 127.0.0.1

app:
  api-prefix: /api
  public-end-points: "/auth/api/app/.*"
  auth-service-info:
    name: "auth_service"
    url: http://localhost:8881
    path: ${app.api-prefix}/auth/**

spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0 # Ti le ghi log

# Cấu hình logging
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*' # health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true