server:
  port: 1997

app:
  api-prefix: /api
  public-end-points: "/auth/api/app/.*"
  auth-service-info:
    name: "auth_service"
    url: http://localhost:8881
    path: ${app.api-prefix}/auth/**

spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0 # Ti le ghi log
  # Định nghĩa route fallback
  web:
    flux:
      router:
        - path: /fallback
          handler: myFallbackHandler

# Cấu hình logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      all: true