apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-system
  labels:
    app: rancher
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - name: rancher-http
      port: 8882
      protocol: TCP
      targetPort: 80
    - name: rancher-https-internal
      port: 443
      protocol: TCP
      targetPort: 444
  selector:
    app: rancher
  sessionAffinity: None
