version: '3.8'

services:
  consul:
    image: consul:1.15.2
    container_name: consul
    ports:
      - "8500:8500"  # Giao diện web của Consul
      - "8600:8600"  # Port DNS của Consul
    volumes:
      # - consul_data:/consul/data
      # - consul_logs:/consul/logs
      - ./consul/data:/consul/data
      - ./consul/logs:/consul/logs
      - ./consul/consul-config.json:/consul/consul-config.json
      - ./consul/register-services.sh:/consul/register-services.sh
      - ./consul/loki-service.json:/consul/loki-service.json
      - ./consul/promtail-service.json:/consul/promtail-service.json
      - ./consul/my-service.json:/consul/my-service.json
    command: ["/consul/register-services.sh"]
    # command: ["consul", "agent", "-config-file=/consul/consul-config.json"]
    networks:
      - consul-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.10
    container_name: promtail
    ports:
      - "9080:9080"  # HTTP port
      - "9096:9096"  # gRPC port
    volumes:
      # - promtail_logs:/var/log
      - ./promtail/logs:/var/log
      - ./promtail/promtail-config.yaml:/promtail/promtail-config.yaml
    command: -config.file=/promtail/promtail-config.yaml
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.10
    container_name: loki
    ports:
      - "3100:3100"  # Cổng HTTP cho Loki
      - "9095:9095"  # Cổng gRPC cho Loki (nếu cần)
    volumes:
      # - loki_data:/loki
      - ./loki:/loki
      - ./loki/loki-config.yaml:/loki/loki-config.yaml
    command: -config.expand-env=true -config.file=/loki/loki-config.yaml
    restart: unless-stopped

# volumes:
#  consul_data:
#  consul_logs:
#  promtail_logs:
#  loki_data:

networks:
  consul-network:
