version: '3.8'

services:
  kong_database:
    image: postgres:13.16
    container_name: kong_database
    networks:
      - kong-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: vip.hieuboy
    volumes:
      - ./data:/var/lib/postgresql/data

  kong_gateway:
    image: kong/kong-gateway:3.7.1.2
    container_name: kong_gateway
    networks:
      - kong-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: vip.hieuboy
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_LICENSE_DATA: '{"license":{"payload":{"admin_seats":"1","customer":"Example Company, Inc","dataplanes":"1","license_creation_date":"2024-08-15","license_expiration_date":"2025-08-15","license_key":"00141000017ODj3AAG_a1V41000004wT0OEAU","product_subscription":"Konnect Enterprise","support_plan":"None"},"signature":"6985968131533a967fcc721244a979948b1066967f1e9cd65dbd8eeabe060fc32d894a2945f5e4a03c1cd2198c74e058ac63d28b045c2f1fcec95877bd790e1b","version":"1"}}'
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    volumes:
      - ./logs:/usr/local/kong/logs
    depends_on:
      - kong_database

networks:
  kong-network:
    external: true
    name: kong-network