apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rancher-role-binding
  namespace: cattle-system
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cattle-system
roleRef:
  kind: Role
  name: rancher-role
  apiGroup: rbac.authorization.k8s.io
