server:
  http_listen_port: 9080
  grpc_listen_port: 9096

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: log_system
          __path__: /logs/**/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+ \S+) (?P<level>\S+) (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: '1997-03-21 17:30:00'
      - labels:
          level:
      - drop:
          expression: 'level="DEBUG"'

  - job_name: api_gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: log_api_gateway
          __path__: /logs/**/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: timestamp
            msg: message
      - timestamp:
          source: timestamp
          format: '1997-03-21 17:30:00'
      - labels:
          level:
      - drop:
          expression: 'level="TRACE"'

# server: Cấu hình cổng cho HTTP và gRPC của Promtail.
# positions: Tệp lưu trữ vị trí của các log đã được đọc, để tiếp tục từ nơi ngừng lại.
# clients: URL của Loki để gửi log.
# scrape_configs: Cấu hình thu thập log.
# ---> job_name: Tên của công việc thu thập log.
# ---> static_configs: Cấu hình tĩnh cho các thư mục và file log.
# ---> pipeline_stages: Các bước xử lý log (ví dụ: phân tích log định dạng JSON, xử lý timestamp).