namespace: microservice_springboot
replicaCount: 1
appName: api-gateway
instance: zimji
timezone: Asia/Ho_Chi_Minh
dateFormat: yyyy-MM-dd'T'HH:mm:ssZ
apiKey: test

image:
  repository: your-registry/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: api-gateway
  type: LoadBalancer
  port: 80
  targetPort: 1997

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization:
    targetAverageUtilization: 80

config:
  application: |
    server:
      port: 1997

configMap:
  files:
    application:
      enable: true
      name: api-gateway
      key: application.yml
      path: config/application.yml
      mountPath: /config/application.yml
      subPath: application.yml

# Lay mat khau Database ma hoa Base 64
# PowerShell: [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes('vip.hieuboy'))
# dmlwLmhpZXVib3k=
database:
  name: HieuBoy
  address: localhost
  port: 5432
  username: zimji
  password: dmlwLmhpZXVib3k

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 90
podAntiAffinity:
  enabled: true
nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferred: true