namespace: microservice-springboot
replicaCount: 1
appName: api-gateway
timezone: Asia/Ho_Chi_Minh
dateFormat: yyyy-MM-dd'T'HH:mm:ssZ
apiKey: test

image:
  repository: hieuboyfc/api-gateway
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  name: api-gateway
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization:
    targetAverageUtilization: 80

config:
  application: |
    server:
      port: 8080

configMap:
  files:
    application:
      enable: true
      name: api-gateway
      key: application.yaml
      path: config/application.yaml
      mountPath: /config/application.yaml
      subPath: application.yaml

database:
  name: HieuBoy
  address: localhost
  port: 5432
  username: zimji
  password: dmlwLmhpZXVib3k

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 90

podAntiAffinity:
  enabled: true
nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferred:
      - weight: 1
        preference:
          matchExpressions:
            - key: kubernetes.io/election
              operator: In
              values:
                - true
