groups:
  - name: example
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: 'critical'
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "Instance {{ $labels.instance }} has been down for more than 5 minutes."

      - alert: HighCpuUsage
        expr: avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance) < 0.1
        for: 10m
        labels:
          severity: 'warning'
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage has been above 90% for more than 10 minutes."

# alert: Tên của cảnh báo.
# expr: Biểu thức PromQL xác định điều kiện kích hoạt cảnh báo.
# for: Thời gian mà điều kiện phải đúng trước khi cảnh báo được kích hoạt.
# labels: Nhãn cho cảnh báo.
# annotations: Thông tin bổ sung cho cảnh báo như summary và description.