server:
  port: 1997

app:
  api-prefix: /api
  public-end-points: "/auth/api/app/.*"
  auth-service-info:
    name: "auth_service"
    url: http://localhost:8881
    path: ${app.api-prefix}/auth/**

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*" # Bao gồm tất cả các điểm kết nối như health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true # Kích hoạt điểm kết nối Prometheus
  metrics:
    enable:
      all: true # Kích hoạt tất cả các chỉ số metrics
  server:
    port: 1234 # Cấu hình cổng cho server Actuator