version: '3.8'

services:
  postgres:
    image: postgres:13.16
    container_name: postgres_db
    environment:
      POSTGRES_USER: zimji
      POSTGRES_PASSWORD: vip.hieuboy
      POSTGRES_DB: HieuBoy
    ports:
      - "5433:5433"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
    name: postgres-network