version: '3.8'

services:
  redis_6380:
    image: redis:latest
    container_name: redis_6380
    ports:
      - "6380:6379"
    volumes:
      - ./conf/redis-6380.conf:/usr/local/etc/redis/redis.conf
      - redis-data-6380:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network

  redis_6381:
    image: redis:latest
    container_name: redis_6381
    ports:
      - "6381:6379"
    volumes:
      - ./conf/redis-6381.conf:/usr/local/etc/redis/redis.conf
      - redis-data-6381:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network

  redis_6382:
    image: redis:latest
    container_name: redis_6382
    ports:
      - "6382:6379"
    volumes:
      - ./conf/redis-6382.conf:/usr/local/etc/redis/redis.conf
      - redis-data-6382:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network

  redis_6383:
    image: redis:latest
    container_name: redis_6383
    ports:
      - "6383:6379"
    volumes:
      - ./conf/redis-6383.conf:/usr/local/etc/redis/redis.conf
      - redis-data-6383:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network

  redis_6384:
    image: redis:latest
    container_name: redis_6384
    ports:
      - "6384:6379"
    volumes:
      - ./conf/redis-6384.conf:/usr/local/etc/redis/redis.conf
      - redis-data-6384:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network

  redis_6385:
    image: redis:latest
    container_name: redis_6385
    ports:
      - "6385:6379"
    volumes:
      - ./conf/redis-6385.conf:/usr/local/etc/redis/redis.conf
      - redis-data-6385:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - "8001:8001"
    networks:
      - redis-network

volumes:
  redis-data-6380:
    driver: local
  redis-data-6381:
    driver: local
  redis-data-6382:
    driver: local
  redis-data-6383:
    driver: local
  redis-data-6384:
    driver: local
  redis-data-6385:
    driver: local

networks:
  redis-network:
    driver: bridge
