@echo off
echo --- Starting Docker Compose...
@echo off

:: Khởi động Redis Cluster 6380...
echo Starting Redis Cluster 6380...
docker-compose up -d redis_6380
echo Waiting for Redis Cluster 6380 to start...
timeout /t 10 /nobreak > NUL

:: Khởi động Redis Cluster 6381...
echo Starting Redis Cluster 6381...
docker-compose up -d redis_6381
echo Waiting for Redis Cluster 6381 to start...
timeout /t 10 /nobreak > NUL

:: Khởi động Redis Cluster 6382...
echo Starting Redis Cluster 6382...
docker-compose up -d redis_6382
echo Waiting for Redis Cluster 6382 to start...
timeout /t 10 /nobreak > NUL

:: Khởi động Redis Cluster 6383...
echo Starting Redis Cluster 6383...
docker-compose up -d redis_6383
echo Waiting for Redis Cluster 6383 to start...
timeout /t 10 /nobreak > NUL

:: Khởi động Redis Cluster 6384...
echo Starting Redis Cluster 6384...
docker-compose up -d redis_6384
echo Waiting for Redis Cluster 6384 to start...
timeout /t 10 /nobreak > NUL

:: Khởi động Redis Cluster 6385...
echo Starting Redis Cluster 6385...
docker-compose up -d redis_6385
echo Waiting for Redis Cluster 6385 to start...
timeout /t 10 /nobreak > NUL

echo Waiting for Redis to start...
timeout /t 5 /nobreak > NUL

:: Khởi tạo Redis Cluster...
echo Creating Redis Cluster...
docker exec -it redis_6380 redis-cli --cluster create ^
  redis_6380:6380 ^
  redis_6381:6381 ^
  redis_6382:6382 ^
  redis_6383:6383 ^
  redis_6384:6384 ^
  redis_6385:6385 ^
  --cluster-replicas 1
timeout /t 5 /nobreak > NUL

echo Redis Cluster setup complete.

:: Khởi động Redis Insight...
echo Starting Redis Insight...
docker-compose up -d redis_insight
echo Waiting for Redis Insight to start...
timeout /t 10 /nobreak > NUL

echo All Services have been started!
