apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  application.yaml: |
    server:
      port: 1997
    app:
      api-prefix: /api
      public-end-points: "/auth/api/app/.*"
      auth-service-info:
        name: "auth_service"
        url: http://localhost:8881
        path: ${app.api-prefix}/auth/**
    spring:
      application:
        name: api-gateway
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        prometheus:
          enabled: true
      metrics:
        enable:
          all: true
      server:
        port: 1234