{{- $files := .Files }}
{{- $namespace := .Values.namespace }}
{{- range $key,$value := .Values.configMap.files }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $value.name }}
  namespace: {{ $namespace }}
data:
  {{ $value.key }}: {{ $files.Get $value.path | quote }}
  {{end}}