apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}-network-policy
spec:
  podSelector:
    matchLabels:
      {{ - include "selectorLabels" . | nindent 6 }}
  ingress:
      ports:
        - name: {{ .Values.service.name }}
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
