apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 443
          protocol: TCP
