apiVersion: v1
kind: Secret
metadata:
  name: db-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_USERNAME: {{ .Values.database.username | quote }}
  API_KEY: {{ .Values.apiKey }}
