name: CI/CD Main Pipeline

on:
  push:
    branches:
      - dev
      - qas
      - prod
  pull_request:
    branches:
      - dev
      - qas
      - prod

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Determine changed services
        id: determine-changes
        run: |
          PREVIOUS_SHA=$(git rev-parse HEAD^ || echo "No previous commit")
          changes=$(git diff --name-only $PREVIOUS_SHA HEAD || true)
          echo "Changed files:"
          echo "$changes"

          # Initialize environment variables for changed services
          if echo "$changes" | grep -q '^api-gateway/'; then
            echo "api-gateway changed" >> $GITHUB_ENV
          fi

          if echo "$changes" | grep -q '^auth-service/'; then
            echo "auth-service changed" >> $GITHUB_ENV
          fi

      - name: Trigger api-gateway CI/CD
        if: env.api-gateway-changed == 'api-gateway changed'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"ref": "${{ github.ref }}"}' \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/api-gateway.yml/dispatches

      - name: Trigger auth-service CI/CD
        if: env.auth-service-changed == 'auth-service changed'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"ref": "${{ github.ref }}"}' \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/auth-service.yml/dispatches