name: CI/CD Deploy to Kubernetes (Parent)

on:
  push:
    branches:
      - dev
      - qas
      - prod
  pull_request:
    branches:
      - dev
      - qas
      - prod

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, auth-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Determine changed services
        id: changed-services
        run: |
          # Get the list of changed files
          changes=$(git diff --name-only HEAD^ HEAD || true)

          # Initialize empty variable
          CHANGED_SERVICES=""

          # Determine changed services
          if echo "$changes" | grep -q '^api-gateway/'; then
            CHANGED_SERVICES="api-gateway"
          fi
          if echo "$changes" | grep -q '^auth-service/'; then
            CHANGED_SERVICES="auth-service"
          fi

          # Export the result as an environment variable
          echo "CHANGED_SERVICES=$CHANGED_SERVICES" >> $GITHUB_ENV

      - name: Check if service exists
        id: check-service
        run: |
          if [ -d ${{ matrix.service }} ]; then
            echo "${{ matrix.service }} directory exists."
          else
            echo "${{ matrix.service }} directory does not exist. Skipping steps."
            exit 0
          fi

      - name: Grant execute permissions to gradlew
        if: steps.check-service.outputs.exists == 'true'
        run: chmod +x ./${{ matrix.service }}/gradlew

      - name: Build and test for changed services
        if: steps.check-service.outputs.exists == 'true'
        run: |
          if echo "$CHANGED_SERVICES" | grep -q '${{ matrix.service }}'; then
            echo "Building and testing ${{ matrix.service }}"
            cd ${{ matrix.service }}
            ./gradlew build
          else
            echo "Skipping ${{ matrix.service }} as it has not changed"
          fi
        env:
          CHANGED_SERVICES: ${{ env.CHANGED_SERVICES }}
